# Homework 2. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[6.4641e-04, 1.5930e-01, 4.8832e-01, 6.1643e-01, 4.4843e-02, 6.3826e-01,
         6.6746e-01],
        [8.5652e-01, 1.8016e-01, 7.9587e-01, 8.3072e-01, 3.3506e-01, 9.5217e-01,
         5.7997e-01],
        [6.2611e-01, 1.8577e-01, 1.4329e-02, 3.7230e-01, 6.7109e-02, 7.7145e-01,
         5.5974e-01],
        [2.4934e-01, 5.4214e-01, 3.9715e-01, 9.4354e-01, 8.5840e-01, 9.5304e-01,
         8.6928e-01],
        [3.6960e-01, 2.6504e-01, 2.2659e-01, 7.2996e-01, 8.1642e-02, 2.8117e-01,
         1.1657e-01],
        [7.6220e-01, 6.9593e-01, 4.1999e-01, 7.5034e-01, 5.2963e-01, 6.7771e-01,
         9.0687e-01],
        [7.6916e-01, 9.6752e-01, 3.6548e-01, 9.0952e-02, 7.6087e-01, 6.3043e-01,
         9.5272e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
m = torch.rand(1, 7)
print(m)
# Perform matrix multiplication
y = torch.mm(x, m.t()) 
y

tensor([[0.2991, 0.7811, 0.9026, 0.3708, 0.9839, 0.3817, 0.0492]])


tensor([[1.1145],
        [2.1449],
        [0.8714],
        [2.4575],
        [0.9861],
        [2.2533],
        [2.3856]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7, 7)
m = torch.rand(1, 7)
# Matrix multiply tensors
y = torch.mm(x, m.t())
y

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())

# Create two random tensors on GPU
x = torch.rand(2, 3).cuda()
y = torch.rand(2, 3).cuda()
x, y # Print tensors 

True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
product = torch.matmul(x, y.t())
product

tensor([[0.3646, 0.4708],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
max = torch.max(product)
# Find min
min = torch.min(product)
max, min # Print max and min

(tensor(0.5617, device='cuda:0'), tensor(0.3646, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
argmax = torch.argmax(product)

# Find arg min
argmin = torch.argmin(product)
argmax, argmin # Print argmax and argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random2 = torch.squeeze(random1)

# Print out tensors and their shapes
random1, random1.shape, random2, random2.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))