## Homework Assignment 1 - NumPy Exercises for Beginners
NumPy is a computational library that helps in speeding up Vector Algebra operations that involve Vectors (Distance between points, Cosine Similarity) and Matrices. Specifically, it helps in constructing powerful n-dimensional arrays that works smoothly with distributed and GPU systems. It is a very handy library and extensively used in the domains of Data Analytics and Machine Learning. Other than Python, it can also be used in tandem with languages like C and Fortran. Being an Open Source Library under a liberal BSD license, it is developed and maintained publicly on GitHub. 

### 1. Import the numpy package under the name `np`

In [1]:
import numpy as np

### 2. Create random vector of size 10 and replace the maximum value by 0

In [8]:
vector = np.random.rand(10)
print(vector)
vector[vector.argmax()] = 0
vector

[0.5094695  0.3076282  0.35233873 0.64010877 0.14087851 0.3898219
 0.19837608 0.0388532  0.42277616 0.58077464]


array([0.5094695 , 0.3076282 , 0.35233873, 0.        , 0.14087851,
       0.3898219 , 0.19837608, 0.0388532 , 0.42277616, 0.58077464])

### 3. Create a 5*5 martrix whose main diagonal elements as `1,2,3,4,5` and other elements as `0`

In [9]:
matrix = np.diag([1,2,3,4,5])
matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### 4. Create a 10*10 martrix whose boundary values as 1 and internal values as 0

In [10]:
# Create a 10*10 martrix whose boundary values as 1 and internal values as 0
matrix = np.ones((10,10))
matrix[1:-1,1:-1] = 0
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])